name: 🐛 버그 수정 요청
description: 애플리케이션에서 발생한 버그에 대한 수정 요청
title: "fix: [버그 요약]"
labels: [ "bug", "fix" ]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: 버그 설명
      placeholder: 어떤 문제가 발생했는지 자세히 작성해주세요.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 재현 방법
      placeholder: |
        1. 어떤 페이지에서
        2. 어떤 동작을 하면
        3. 어떤 결과가 나오는지
    validations:
      required: true

  - type: input
    id: expected-behavior
    attributes:
      label: 기대 동작
      placeholder: 버그가 없었다면 어떤 동작이 되어야 하나요?
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: 스크린샷 (선택)
      description: 시각적인 버그라면 첨부해주세요.