name: Backend CI/CD Pipeline

# master 브랜치에 push 또는 PR이 merge 될 때 실행
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle 빌드 및 테스트
        run: |
          ./gradlew clean build --no-daemon -x test

      - name: 빌드 결과 업로드
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar

  deploy:
    name: Deploy to Server
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout 코드
        uses: actions/checkout@v3

      - name: SSH 키 등록
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./deploy

      - name: Debug list deploy directory
        run: ls -l deploy/

      - name: 서버에 JAR 전송
        run: |
          scp -o StrictHostKeyChecking=no \
            deploy/*.jar \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/app/app.jar

      - name: 원격에서 서비스 재시작
        run: |
          ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo systemctl restart ${{ secrets.SERVICE_NAME }}"